version: '3'

volumes:
  postgres:
    driver: 'local'

services:
  postgres:
    image: 'postgres'
    volumes: ['postgres:/var/lib/postgresql/data']
    ports: ['5432:5432']

  ennui:
    image: 'ennui:v0.1.5'
    ports: ['8089:8089']
