version: '3'

volumes:
  postgres:
    driver: 'local'

services:
  postgres:
    image: 'postgres'
    volumes: ['postgres:/var/lib/postgresql/data']
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password123'
    ports: ['5432:5432']

  ennui:
    image: 'bundle.bar/u/pmengelbert/ennui:${TAG}'
    ports: ['8089:8089']
