version: '3'

volumes:
  postgres:
    driver: 'local'

services:
  postgres:
    image: 'postgres'
    volumes: ['postgres:/var/lib/postgresql/data']
    env_file: ['./postgres.env']
    ports: ['5432:5432']

  ennui:
    image: 'bundle.bar/u/pmengelbert/ennui:latest'
    ports: ['8089:8089']
